language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install pep8
  - pip install coveralls
script:
  - pep8 --ignore=E501 bigfont
  - nosetests --with-coverage --cover-package=bigfont
after_success:
  - coveralls